version: '3.4'

services:
  db:
    image: mysql:8.0
    container_name: tog-do-db
    restart: always
    environment:
      MYSQL_DATABASE: 'tog_do_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  # togdo:
  #    image: togdo
  #    container_name: app
  #    build:
  #      context: .
  #      dockerfile: ./Dockerfile
  #    environment:
  #      NODE_ENV: production
  #      DB_NAME: tog_do_db
  #      DB_USER: admin
  #      DB_PASS: admin
  #      DB_HOST: localhost
  #      DB_PORT: 3306    
  #    ports:
  #      - 3000:3000